In [2]:
import numpy as np
import pandas as pd
from numpy import array
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split,cross_val_score,cross_validate,GridSearchCV
from sklearn.metrics import confusion_matrix, accuracy_score, mean_squared_error, multilabel_confusion_matrix, classification_report

In [3]:
df = pd.read_csv('SpotifyFeatures_new.csv',encoding='latin-1')


# Drop columns
dropped_columns = ['genre', 'artist_name', 'track_name','track_id', 'mode', 'duration_ms', 'tempo', 'energy', 'acousticness']
df.drop(columns=dropped_columns, inplace=True)

# Normalize data
X, y = df.drop(columns='popularity'), df['popularity']
X = (X-X.min())/(X.max()-X.min())

y = ((y-1)//20)+1

print(y)
print(X)

0         1
1         1
2         1
3         1
4         1
         ..
169679    5
169680    5
169681    5
169682    5
169683    5
Name: popularity, Length: 169684, dtype: int64
        danceability  instrumentalness  liveness  loudness  speechiness  \
0           0.541895          0.029930  0.095251  0.808082     0.024661   
1           0.503272          0.621622  0.369907  0.745076     0.302498   
2           0.268319          0.283283  0.509254  0.730983     0.014712   
3           0.477524          0.004755  0.113427  0.778349     0.004551   
4           0.423882          0.376376  0.097271  0.701589     0.016617   
...              ...               ...       ...       ...          ...   
169679      0.754318          0.000000  0.061222  0.834202     0.025826   
169680      0.729643          0.000002  0.048196  0.886194     0.039268   
169681      0.717841          0.000000  0.097271  0.839256     0.073561   
169682      0.832636          0.000002  0.092222  0.801730     0.164903

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state=5)

mlp = MLPClassifier(solver = 'sgd',activation="logistic", hidden_layer_sizes=(16, 12, 8), learning_rate_init=0.2, max_iter=400, random_state=1)
nn_model = mlp.fit(X_train, y_train)


In [9]:
import joblib
# save the model to disk
filename = 'finalized_model.joblib'
joblib.dump(nn_model, filename)

['finalized_model.joblib']

In [10]:
# Make prediction
y_pred = nn_model.predict(X_test)

# Accuracy
print("\nAccuracy: ")
print(accuracy_score(y_test, y_pred))

# MSE
print('\nMSE: ')
print(mean_squared_error(y_test,y_pred))

# The map of label and their precision and recall
print("\nPrecision and recall:" )
print(classification_report(y_test, y_pred))


print("Confusion matrix: ")
matrix = confusion_matrix(y_test, y_pred)
multi_matrix = multilabel_confusion_matrix(y_test, y_pred)
print(multi_matrix)


Accuracy: 
0.5147479152547367

MSE: 
0.6447535138639243

Precision and recall:
              precision    recall  f1-score   support

           1       0.64      0.27      0.38      5149
           2       0.51      0.63      0.56     13755
           3       0.50      0.60      0.55     12322
           4       0.00      0.00      0.00      2614
           5       0.00      0.00      0.00        97

    accuracy                           0.51     33937
   macro avg       0.33      0.30      0.30     33937
weighted avg       0.49      0.51      0.48     33937

Confusion matrix: 


C:\Users\Anna Feng\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Anna Feng\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Anna Feng\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


[[[27997   791]
  [ 3762  1387]]

 [[11839  8343]
  [ 5110  8645]]

 [[14281  7334]
  [ 4885  7437]]

 [[31323     0]
  [ 2614     0]]

 [[33840     0]
  [   97     0]]]
