In [1]:
import numpy as np
import pandas as pd
from numpy import array
from sklearn.ensemble import RandomForestClassifier, BaggingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split,cross_val_score,cross_validate,GridSearchCV
from sklearn.metrics import confusion_matrix, accuracy_score, mean_squared_error, multilabel_confusion_matrix, classification_report

In [2]:
df = pd.read_csv("SpotifyWithDate.csv")
# Normalize data
X, y = df.drop(columns=['popularity', 'track_id']), df['popularity']
X = (X-X.min())/(X.max()-X.min())
y = ((y-1)//20)+1

In [3]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.30, random_state=5)

rf_cla = RandomForestClassifier(n_estimators=1500,random_state=1)

In [4]:
rf_cla.fit(X_train, y_train)

RandomForestClassifier(n_estimators=1500, random_state=1)

In [5]:
# Make prediction
y_pred = rf_cla.predict(X_test)

# Accuracy
print("\nAccuracy: ")
print(accuracy_score(y_test, y_pred))

# MSE
print('\nMSE: ')
print(mean_squared_error(y_test,y_pred))

# The map of label and their precision and recall
print("\nPrecision and recall:" )
print(classification_report(y_test, y_pred))


print("Confusion matrix: ")
matrix = confusion_matrix(y_test, y_pred)
multi_matrix = multilabel_confusion_matrix(y_test, y_pred)
print(multi_matrix)


Accuracy: 
0.4934199837530463

MSE: 
0.7262388302193339

Precision and recall:
              precision    recall  f1-score   support

           1       0.63      0.37      0.47     10255
           2       0.48      0.68      0.57     17745
           3       0.43      0.41      0.42     12089
           4       0.75      0.12      0.21      2840
           5       0.81      0.46      0.58       156

    accuracy                           0.49     43085
   macro avg       0.62      0.41      0.45     43085
weighted avg       0.52      0.49      0.48     43085

Confusion matrix: 
[[[30580  2250]
  [ 6435  3820]]

 [[12346 12994]
  [ 5625 12120]]

 [[24549  6447]
  [ 7190  4899]]

 [[40127   118]
  [ 2491   349]]

 [[42912    17]
  [   85    71]]]


In [8]:
def getdistribution(data):
    distribution = dict()
    for value in data:
        if value in distribution:
            distribution[value] += 1
        else:
            distribution[value] = 1
    return distribution

dist = getdistribution(y)
print(f'For popularity distrubtion {dist}') # print frequency

For popularity distrubtion {1: 34209, 2: 59120, 3: 40131, 4: 9622, 5: 534}
